
version: '3'

services:
    db:
      image: mysql
      ports:
      - "${DB_PORT}:${DB_PORT}"
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - scraping
      volumes:
      - mysql-data:/var/lib/mysql
      - ./model/schema.sql:/docker-entrypoint-initdb.d/schema.sql 

    app:
      build: .
      restart: always
      depends_on:
         db:
          condition: service_healthy
      ports:
        - "${PORT}:${PORT}"
      networks:
        - scraping


networks:
  scraping:

volumes:
  mysql-data:
