CREATE DATABASE IF NOT EXISTS scraping ;
use scraping;

CREATE TABLE  IF NOT EXISTS story(
	id INT AUTO_INCREMENT PRIMARY Key,
	title TEXT NOT NULL,
	link  TEXT NOT NULL,
	site TEXT,
	upvotes INT,
	postTime BIGINT,
	postedAt DATETIME,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);